Dictionary CI: support PRs from forks

diff --git a/.github/workflows/dictionary_push.yaml b/.github/workflows/dictionary_push.yaml
--- a/.github/workflows/dictionary_push.yaml
+++ b/.github/workflows/dictionary_push.yaml
@@ -46,8 +46,36 @@ jobs:
   test:
     runs-on: ubuntu-20.04
     steps:
+    - name: Check PR
+      run: |
+        echo Event name: ${{ github.event_name }}
+        if [[ ${{ github.event_name }} = "pull_request" || ${{ github.event_name }} = "pull_request_target" ]]; then
+          is_fork=`curl --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.event.repository.full_name }}/pulls/${{github.event.number}} | jq -r .head.repo.fork`
+          echo Is this a fork? $is_fork
+          echo "IS_FORK=$is_fork" >> $GITHUB_ENV
+          if [ $is_fork = "true" ]; then
+            labels=`curl -s --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.event.repository.full_name }}/issues/${{github.event.number}}/labels | jq -r '.[].name'`
+            echo Labels: $labels
+            if [[ ! " ${labels[*]} " =~ "safe to test" ]]; then
+              echo "ERROR: PRs from forks must be labeled with 'safe to test' to run the CI"
+              exit 1
+            fi
+          fi
+        fi
     - name: checkout
-      uses: actions/checkout@v4
+      run: |
+        # checkout the code - this supports checking out from a private fork
+        git clone https://Bot:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.event.repository.full_name }}
+        cd ${{ github.event.repository.name }}
+        if [ ${{ github.event_name }} = "push" ]; then
+          branch=${GITHUB_REF#refs/*/}
+          echo Push event: checking out branch $branch
+          git checkout $branch
+        else # this is a pull request
+          echo Pull request event: checking out branch from PR ${{github.event.number}}
+          git fetch origin pull/${{github.event.number}}/head:localbranch
+          git checkout localbranch
+        fi
     - name: Setup Python
       uses: actions/setup-python@v4
       with:
@@ -101,7 +129,13 @@ jobs:
         poetry run ./run_tests.sh
         echo "Number of schemas in artifact"
         grep -o ".yaml\"" artifacts/schema.json | wc -l
-        aws s3 cp artifacts/schema.json s3://${{ inputs.BUCKET }}/${{ inputs.DIRECTORY }}/$GITHUB_REF_NAME/schema.json --region ${{ inputs.REGION }}
+
+        if [ ${{ env.IS_FORK }} = "true" ]; then
+          branch=fork-pr-${{github.event.number}}
+        else
+          branch=$GITHUB_REF_NAME
+        fi
+        aws s3 cp artifacts/schema.json s3://${{ inputs.BUCKET }}/${{ inputs.DIRECTORY }}/$branch/schema.json --region ${{ inputs.REGION }}
 
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.DICT_AWS_ACCESS_KEY_ID }}
