Update integration_tests.yaml

diff --git a/.github/workflows/integration_tests.yaml b/.github/workflows/integration_tests.yaml
--- a/.github/workflows/integration_tests.yaml
+++ b/.github/workflows/integration_tests.yaml
@@ -207,22 +207,6 @@ jobs:
             with:
               version: latest
 
-          # # Setup GCP
-          # - name: 'Authenticate with GCP'
-          #   uses: 'google-github-actions/auth@v2'
-          #   with:
-          #     workload_identity_provider: 'projects/397853036191/locations/global/workloadIdentityPools/github-helm-ci-identity-pool/providers/github-provider'
-          #     service_account: 'gh-actions-sa@dcf-integration.iam.gserviceaccount.com'
-
-          # - name: 'Set up Cloud SDK'
-          #   uses: 'google-github-actions/setup-gcloud@v2'
-          #   with:
-          #     version: '>= 363.0.0'
-
-          # - name: 'Use gcloud CLI'
-          #   run: 'gcloud info'
-
-
           # Install gen3-integration-tests dependencies
           # wamerican: data-simulator needs "/usr/share/dict/words" to generate data that isn't random strings
           - name: Install dependencies
@@ -421,12 +405,6 @@ jobs:
                 echo "PR_ERROR_MSG=Test(s) failures encountered in PR" >> $GITHUB_ENV
               fi
 
-          # - name: Helm uninstall environment
-          #   id: helm_uninstall_env
-          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
-          #   run: |
-          #     helm uninstall $NAMESPACE -n $NAMESPACE
-
           - name: Merge report.md if failed tests were rerun
             id: merge_report_md_on_rerun
             if: ${{ env.SKIP_TESTS != 'true' && env.FAILED_TEST_SUITES != '' }}
@@ -459,48 +437,33 @@ jobs:
                 fi
               fi
 
-          - name: Upload allure report to S3
-            id: upload_allure_report
+          - name: Upload files to S3
+            id: upload_files_to_s3
             if: ${{ env.SKIP_TESTS != 'true' && steps.generate_allure_report.outcome == 'success' }}
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: |
-              echo -e "\n\n******* Upload reports to S3 *******" >> logs/gh_action_logs.txt
+              echo -e "\n\n******* Upload reports/gh action logs to S3 *******" >> logs/gh_action_logs.txt
               if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
                 DATE=$(date +%Y%m%d)
                 aws s3 sync ./allure-report s3://ci-allure-reports/nightly-run-$CI_ENV/$DATE/$RUN_NUM/$ATTEMPT_NUM >> logs/gh_action_logs.txt 2>&1
                 if [ -n "$FAILED_TEST_SUITES" ]; then
                   aws s3 sync ./rerun-allure-report s3://ci-allure-reports/nightly-run-$CI_ENV/$DATE-rerun/$RUN_NUM/$ATTEMPT_NUM >> logs/gh_action_logs.txt 2>&1
                 fi
+                aws s3 cp logs/gh_action_logs.txt s3://ci-allure-reports/nightly-run-$CI_ENV/$DATE/$RUN_NUM/$ATTEMPT_NUM/gh_action_logs.txt >> logs/gh_action_logs.txt 2>&1
               else
                 aws s3 sync ./allure-report s3://ci-allure-reports/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM >> logs/gh_action_logs.txt 2>&1
                 if [ -n "$FAILED_TEST_SUITES" ]; then
                   aws s3 sync ./rerun-allure-report s3://ci-allure-reports/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM-rerun >> logs/gh_action_logs.txt 2>&1
                 fi
-              fi
-              if [ $? -ne 0 ]; then
-                echo "PR_ERROR_MSG=Failed to upload allure report to s3 bucket" >> $GITHUB_ENV
-              fi
-
-          - name: Upload logs to S3
-            id: upload_gh_action_logs
-            if: ${{ env.SKIP_TESTS != 'true' && (steps.prep_ci_env.outcome == 'success' || steps.prep_ci_env.outcome == 'failure') }}
-            continue-on-error: true  # if this fails, we still need to run clean-up steps
-            run: |
-              echo -e "\n\n******** Upload GH action logs to S3 ********" >> logs/gh_action_logs.txt
-              if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
-                DATE=$(date +%Y%m%d)
-                aws s3 cp logs/gh_action_logs.txt s3://ci-allure-reports/nightly-run-$CI_ENV/$DATE/$RUN_NUM/$ATTEMPT_NUM/gh_action_logs.txt >> logs/gh_action_logs.txt 2>&1
-              else
                 aws s3 cp logs/gh_action_logs.txt s3://ci-allure-reports/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM/gh_action_logs.txt >> logs/gh_action_logs.txt 2>&1
               fi
               if [ $? -ne 0 ]; then
                 echo "PR_ERROR_MSG=Failed to upload allure report to s3 bucket" >> $GITHUB_ENV
               fi
 
-
           - name: Generate markdown report
             id: generate_md_report
-            if: ${{ env.SKIP_TESTS != 'true' && (steps.upload_allure_report.outcome == 'success' || steps.upload_gh_action_logs.outcome == 'success') }}
+            if: ${{ env.SKIP_TESTS != 'true' && steps.upload_files_to_s3.outcome == 'success' }}
             continue-on-error: true
             # It is possible for env is prepped but tests error out, the pod logs will help in debugging env issues
             run: |
@@ -511,40 +474,26 @@ jobs:
                 fi
                 echo -e "\n${{ env.PR_ERROR_MSG }}" >> output/report.md
               fi
-              if [ "${{ steps.upload_allure_report.outcome }}" == "success" ]; then
+              if [ "${{ steps.upload_files_to_s3.outcome }}" == "success" ]; then
                 if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
                   DATE=$(date +%Y%m%d)
                   echo -e "\nPlease find the detailed integration test report [here](https://allure.ci.planx-pla.net/nightly-run-$CI_ENV/$DATE/$RUN_NUM/$ATTEMPT_NUM/index.html)" >> output/report.md
                   if [ -n "$FAILED_TEST_SUITES" ]; then
                     echo -e "\nPlease find the detailed integration test report after rerunning failed tests [here](https://allure.ci.planx-pla.net/nightly-run-$CI_ENV/$DATE-rerun/$RUN_NUM/$ATTEMPT_NUM/index.html)" >> output/report.md
                   fi
+                  echo -e "\nPlease find the Github Action logs [here](https://allure.ci.planx-pla.net/nightly-run-$CI_ENV/$DATE/$RUN_NUM/$ATTEMPT_NUM/gh_action_logs.txt)" >> output/report.md
                 else
                   echo -e "\nPlease find the detailed integration test report [here](https://allure.ci.planx-pla.net/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM/index.html)" >> output/report.md
                   if [ -n "$FAILED_TEST_SUITES" ]; then
                     echo -e "\nPlease find the detailed integration test report after rerunning failed tests [here](https://allure.ci.planx-pla.net/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM-rerun/index.html)" >> output/report.md
                   fi
-                fi
-              fi
-              if [ "${{ steps.upload_gh_action_logs.outcome }}" == "success" ]; then
-                if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
-                  DATE=$(date +%Y%m%d)
-                  echo -e "\nPlease find the Github Action logs [here](https://allure.ci.planx-pla.net/nightly-run-$CI_ENV/$DATE/$RUN_NUM/$ATTEMPT_NUM/gh_action_logs.txt)" >> output/report.md
-                else
                   echo -e "\nPlease find the Github Action logs [here](https://allure.ci.planx-pla.net/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM/gh_action_logs.txt)" >> output/report.md
                 fi
               fi
-              # if [ "${{ steps.upload_analyze_failure_file_logs.outcome }}" == "success" ]; then
-              #   if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
-              #     DATE=$(date +%Y%m%d)
-              #     echo -e "\nPlease find the Github Action logs [here](https://allure.ci.planx-pla.net/nightly-run-$CI_ENV/$DATE/$RUN_NUM/$ATTEMPT_NUM/failure_analysis.txt)" >> output/report.md
-              #   else
-              #     echo -e "\nPlease find the Github Action logs [here](https://allure.ci.planx-pla.net/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM/failure_analysis.txt)" >> output/report.md
-              #   fi
-              # fi
 
           - name: Render report to the PR
             id: publish_md_report
-            if: ${{ env.SKIP_TESTS != 'true' && github.event_name == 'pull_request' && (steps.upload_allure_report.outcome == 'success' || steps.upload_gh_action_logs.outcome == 'success') }}
+            if: ${{ env.SKIP_TESTS != 'true' && github.event_name == 'pull_request' && steps.upload_files_to_s3.outcome == 'success' }}
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: gh pr comment $PR_NUM --body-file output/report.md -R $REPO_FN
             env:
@@ -552,7 +501,7 @@ jobs:
 
           - name: Generate Slack report
             id: generate_slack_report
-            if: ${{ env.SKIP_TESTS != 'true' && (steps.upload_allure_report.outcome == 'success' || steps.upload_gh_action_logs.outcome == 'success') }}
+            if: ${{ env.SKIP_TESTS != 'true' && steps.upload_files_to_s3.outcome == 'success' }}
             continue-on-error: true # if this fails, we still need to run clean-up steps
             run: poetry run python -m gen3_ci.scripts.generate_slack_report
 
@@ -574,6 +523,15 @@ jobs:
             run: |
               echo -e "\n\n****** Running Analyze Failures using AI agent ******" >>  logs/gh_action_logs.txt
               poetry run python -m gen3_ci.scripts.analyze_failed_tests_using_ai_agent >> logs/gh_action_logs.txt 2>&1
+              if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
+                DATE=$(date +%Y%m%d)
+                aws s3 cp logs/failure_analysis.txt s3://ci-allure-reports/nightly-run-$CI_ENV/$DATE/$RUN_NUM/$ATTEMPT_NUM/failure_analysis.txt >> logs/gh_action_logs.txt 2>&1
+              else
+                aws s3 cp logs/failure_analysis.txt s3://ci-allure-reports/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM/failure_analysis.txt >> logs/gh_action_logs.txt 2>&1
+              fi
+              if [ $? -ne 0 ]; then
+                echo "PR_ERROR_MSG=Failed to upload failure analysis file to s3 bucket" >> $GITHUB_ENV
+              fi
             env:
               THREAD_TS: ${{ steps.slack_notify.outputs.ts }}
 
@@ -587,22 +545,6 @@ jobs:
               token: ${{ secrets.CI_SLACK_BOT_TOKEN }}
               payload-file-path: "./${{ inputs.WORKING_DIR }}/test_analysis_slack_report.json"
               payload-templated: true
-
-          - name: Upload failure analysis to S3
-            id: upload_analyze_failure_file
-            if: ${{ env.SKIP_TESTS != 'true' && steps.analyze_failures_using_ai_agent.outcome == 'success' }}
-            continue-on-error: true  # if this fails, we still need to run clean-up steps
-            run: |
-              echo -e "\n\n******** Upload analyze failure file to S3 ********" >> logs/gh_action_logs.txt
-              if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
-                DATE=$(date +%Y%m%d)
-                aws s3 cp logs/failure_analysis.txt s3://ci-allure-reports/nightly-run-$CI_ENV/$DATE/$RUN_NUM/$ATTEMPT_NUM/failure_analysis.txt >> logs/gh_action_logs.txt 2>&1
-              else
-                aws s3 cp logs/failure_analysis.txt s3://ci-allure-reports/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM/failure_analysis.txt >> logs/gh_action_logs.txt 2>&1
-              fi
-              if [ $? -ne 0 ]; then
-                echo "PR_ERROR_MSG=Failed to upload failure analysis file to s3 bucket" >> $GITHUB_ENV
-              fi
 
           - name: Mark workflow as failed for unsuccessful test runs
             if: ${{ env.SKIP_TESTS != 'true' && steps.run_service_tests.outcome != 'success' && steps.run_tests.outcome != 'success' && steps.rerun_failed_tests.outcome != 'success' }}
