Enable Analyze Failures (#242)
* Enable Analyze Failures

* Update integration_tests.yaml

* Update integration_tests.yaml

* Update integration_tests.yaml

* Update integration_tests.yaml

* Update integration_tests.yaml

* Update integration_tests.yaml

* Update integration_tests.yaml

diff --git a/.github/workflows/integration_tests.yaml b/.github/workflows/integration_tests.yaml
--- a/.github/workflows/integration_tests.yaml
+++ b/.github/workflows/integration_tests.yaml
@@ -668,35 +668,57 @@ jobs:
               payload-file-path: "./${{ inputs.WORKING_DIR }}/slack_report.json"
               payload-templated: true
 
-          # - name: Analyze Failures using AI agent
-          #   id: analyze_failures_using_ai_agent
-          #   if: ${{ env.SKIP_TESTS != 'true' && inputs.EXTERNAL_TO_CTDS != 'true' && (steps.prep_ci_env.outcome == 'failure' || ((steps.run_service_tests.outcome == 'failure' || steps.run_tests.outcome == 'failure') && steps.rerun_failed_tests.outcome != 'success')) }}
-          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
-          #   run: |
-          #     echo -e "\n\n****** Running Analyze Failures using AI agent ******" >>  logs/gh_action_logs.txt
-          #     poetry run python -m gen3_ci.scripts.analyze_failed_tests_using_ai_agent >> logs/gh_action_logs.txt 2>&1
-          #     if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
-          #       DATE=$(date +%Y%m%d)
-          #       aws s3 cp logs/failure_analysis.txt s3://ci-allure-reports/nightly-run-$CI_ENV/$DATE/$RUN_NUM/$ATTEMPT_NUM/failure_analysis.txt >> logs/gh_action_logs.txt 2>&1
-          #     else
-          #       aws s3 cp logs/failure_analysis.txt s3://ci-allure-reports/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM/failure_analysis.txt >> logs/gh_action_logs.txt 2>&1
-          #     fi
-          #     if [ $? -ne 0 ]; then
-          #       echo "PR_ERROR_MSG=Failed to run analyze failures using ai agent step" >> $GITHUB_ENV
-          #     fi
-          #   env:
-          #     THREAD_TS: ${{ steps.slack_notify.outputs.ts }}
+          - name: Analyze Failures using AI agent
+            id: analyze_failures_using_ai_agent
+            if: ${{ env.SKIP_TESTS != 'true' && inputs.EXTERNAL_TO_CTDS != 'true' && (steps.prep_ci_env.outcome == 'failure' || ((steps.run_service_tests.outcome == 'failure' || steps.run_tests.outcome == 'failure') && steps.rerun_failed_tests.outcome != 'success')) }}
+            continue-on-error: true  # if this fails, we still need to run clean-up steps
+            run: |
+              echo -e "\n\n****** Running Analyze Failures using AI agent ******" >>  logs/gh_action_logs.txt
+              poetry run python -m gen3_ci.scripts.analyze_failed_tests_using_ai_agent 
+              if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
+                DATE=$(date +%Y%m%d)
+                aws s3 cp logs/failure_analysis.txt s3://ci-allure-reports/nightly-run-$CI_ENV/$DATE/$RUN_NUM/$ATTEMPT_NUM/failure_analysis.txt >> logs/gh_action_logs.txt 2>&1
+              else
+                aws s3 cp logs/failure_analysis.txt s3://ci-allure-reports/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM/failure_analysis.txt >> logs/gh_action_logs.txt 2>&1
+              fi
+              if [ $? -ne 0 ]; then
+                echo "PR_ERROR_MSG=Failed to run analyze failures using ai agent step" >> $GITHUB_ENV
+              fi
+            env:
+              THREAD_TS: ${{ steps.slack_notify.outputs.ts }}
 
-          # - name: Publish test analysis on same slack thread
-          #   id: publish_test_analysis
-          #   if: ${{ env.SKIP_TESTS != 'true' && inputs.EXTERNAL_TO_CTDS != 'true' && steps.analyze_failures_using_ai_agent.outcome == 'success' }}
-          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
-          #   uses: slackapi/slack-github-action@v2.0.0
-          #   with:
-          #     method: chat.postMessage
-          #     token: ${{ secrets.CI_SLACK_BOT_TOKEN }}
-          #     payload-file-path: "./${{ inputs.WORKING_DIR }}/test_analysis_slack_report.json"
-          #     payload-templated: true
+          - name: Publish test analysis on same slack thread
+            id: publish_test_analysis
+            if: ${{ env.SKIP_TESTS != 'true' && inputs.EXTERNAL_TO_CTDS != 'true' && steps.analyze_failures_using_ai_agent.outcome == 'success' }}
+            continue-on-error: true  # if this fails, we still need to run clean-up steps
+            uses: slackapi/slack-github-action@v2.0.0
+            with:
+              method: chat.postMessage
+              token: ${{ secrets.CI_SLACK_BOT_TOKEN }}
+              payload-file-path: "./${{ inputs.WORKING_DIR }}/test_analysis_slack_report.json"
+              payload-templated: true
+
+          - name: Generate markdown report for test analysis
+            id: generate_md_report_test_analysis
+            if: ${{ env.SKIP_TESTS != 'true' && github.event_name == 'pull_request' && inputs.EXTERNAL_TO_CTDS != 'true' && steps.analyze_failures_using_ai_agent.outcome == 'success' }}
+            continue-on-error: true
+            run: |
+              touch output/report_test_analysis.md
+              if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
+                echo -e "\nPlease find the detailed test analysis report [here](https://allure.ci.planx-pla.net/nightly-run-$CI_ENV/$DATE/$RUN_NUM/$ATTEMPT_NUM/failure_analysis.txt)" >> output/report_test_analysis.md
+              else
+                echo -e "\nPlease find the detailed test analysis report [here](https://allure.ci.planx-pla.net/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM/failure_analysis.txt)" >> output/report_test_analysis.md
+              fi
+
+          - name: Render report to the PR
+            id: publish_md_report_test_analysis
+            if: ${{ env.SKIP_TESTS != 'true' && github.event_name == 'pull_request' && steps.generate_md_report_test_analysis.outcome == 'success' }}
+            continue-on-error: true  # if this fails, we still need to run clean-up steps
+            run: |
+              sed -i "1i## Test Analysis" output/report_test_analysis.md
+              gh pr comment $PR_NUM --body-file output/report_test_analysis.md -R $REPO_FN
+            env:
+              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
           - name: Mark workflow as failed for unsuccessful test runs
             if: ${{ env.SKIP_TESTS != 'true' && steps.run_service_tests.outcome != 'success' && steps.run_tests.outcome != 'success' && steps.rerun_failed_tests.outcome != 'success' }}
