Update integration_tests.yaml

diff --git a/.github/workflows/integration_tests.yaml b/.github/workflows/integration_tests.yaml
--- a/.github/workflows/integration_tests.yaml
+++ b/.github/workflows/integration_tests.yaml
@@ -16,10 +16,6 @@ on:
         required: false
         type: string
         default: master
-      CLOUD_AUTO_BRANCH:
-        required: false
-        type: string
-        default: master
       HELM_BRANCH:
         required: false
         type: string
@@ -28,10 +24,6 @@ on:
         required: false
         type: string
         default: default
-      GEN3_INSTANCE_TYPE:
-        required: false
-        type: string
-        default: HELM_LOCAL
       WORKING_DIR:
         required: false
         type: string
@@ -44,14 +36,6 @@ on:
         required: false
         type: string
     secrets:
-      CI_AWS_ACCESS_KEY_ID:
-        required: false
-      CI_AWS_SECRET_ACCESS_KEY:
-        required: false
-      JENKINS_API_TOKEN:
-        required: false
-      QA_DASHBOARD_S3_PATH:
-        required: true
       CI_TEST_ORCID_USERID:
         required: true
       CI_TEST_ORCID_PASSWORD:
@@ -92,9 +76,6 @@ jobs:
 
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          JENKINS_URL: "https://jenkins.planx-pla.net"
-          JENKINS_USERNAME: "PlanXCyborg"
-          JENKINS_PASSWORD: ${{ secrets.JENKINS_API_TOKEN }}
           REPO: ${{ github.event.repository.name }}
           REPO_FN: ${{ github.event.repository.full_name }}
           BRANCH: ${{ github.event.pull_request.head.ref }}
@@ -109,25 +90,24 @@ jobs:
           CI_TEST_RAS_PASSWORD: ${{ secrets.CI_TEST_RAS_PASSWORD }}
           CI_TEST_RAS_2_EMAIL: ${{ secrets.CI_TEST_RAS_2_EMAIL }}
           CI_TEST_RAS_2_PASSWORD: ${{ secrets.CI_TEST_RAS_2_PASSWORD }}
-          CLOUD_AUTO_BRANCH: ${{ inputs.CLOUD_AUTO_BRANCH }}
           SLACK_CHANNEL: ${{ secrets.CI_SLACK_CHANNEL_ID }}
           EKS_CLUSTER_NAME : ${{ secrets.EKS_CLUSTER_NAME }}
-          GEN3_INSTANCE_TYPE: ${{ inputs.GEN3_INSTANCE_TYPE }}
           GH_WORKSPACE: ${{ github.workspace }}
           HELM_BRANCH: ${{ inputs.HELM_BRANCH }}
           QUAY_REPO: ${{ inputs.QUAY_REPO }}
           IS_NIGHTLY_RUN: ${{ inputs.IS_NIGHTLY_RUN }}
           TEST_LABELS: ${{ inputs.TEST_LABELS }}
+          SKIP_TESTS: 'false'
 
         steps:
-          # Ensure the PR is run under the same org as an Internal PR
-          # and not by external forks/PRs
-          - name: Check if PR is from the same organization
-            if: ${{ github.repository_owner != 'uc-cdis' }}
+          # External PRs will not have access to secrets, so tests cannot run
+          - name: Skip integration tests for external PRs
+            if: ${{ github.event.pull_request.head.repo.fork == true && github.event_name == 'pull_request' }}
             working-directory: ${{ github.workspace }}
             run:  |
-              echo "github.repository_owner - ${{ github.repository_owner }}"
-              echo "Skip pull requests from repositories not within the same organization"
+              echo "Current repo: ${{ github.event.repository.full_name }}"
+              echo "Head Repo: ${{ github.event.pull_request.head.repo.full_name }}"
+              echo "Skipping integration tests for external PRs"
               echo "SKIP_TESTS=true" >> $GITHUB_ENV
 
           # Skip integration tests when the following PR labels are present:
@@ -208,14 +188,14 @@ jobs:
 
           # Setup kubectl
           - name: Set Up kubectl
-            if: ${{  env.GEN3_INSTANCE_TYPE == 'HELM_LOCAL' }}
+            if: ${{ env.SKIP_TESTS != 'true' }}
             uses: azure/setup-kubectl@v3
             with:
               version: latest
 
           # Setup helm
           - name: Set Up Helm
-            if: ${{ env.SKIP_TESTS != 'true' && env.GEN3_INSTANCE_TYPE == 'HELM_LOCAL' }}
+            if: ${{ env.SKIP_TESTS != 'true' }}
             uses: azure/setup-helm@v4.3.0
             with:
               version: latest
@@ -265,7 +245,7 @@ jobs:
 
           # Configure credentials to access cluster.
           - name: Configure AWS Credentials
-            if: ${{ env.SKIP_TESTS != 'true' && env.GEN3_INSTANCE_TYPE == 'HELM_LOCAL' }}
+            if: ${{ env.SKIP_TESTS != 'true' }}
             uses: aws-actions/configure-aws-credentials@v3
             with:
                 role-to-assume: arn:aws:iam::707767160287:role/github-action-role
@@ -275,14 +255,14 @@ jobs:
 
           # Create kubeconfig to point at cluster.
           - name: Update kube config
-            if: ${{ env.SKIP_TESTS != 'true' && env.GEN3_INSTANCE_TYPE == 'HELM_LOCAL' }}
+            if: ${{ env.SKIP_TESTS != 'true' }}
             run: |
               aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region "us-east-1"
 
           # Ensure we do not cross the threshold of maximum number of CI envs allowed
           # The workflow waits if CI infrastructure is at capacity (MAX_ENVS, set to 10)
           - name: Wait for CI environment
-            if: ${{ env.SKIP_TESTS != 'true' && env.GEN3_INSTANCE_TYPE == 'HELM_LOCAL' }}
+            if: ${{ env.SKIP_TESTS != 'true' }}
             id: wait_for_ci_env
             run: |
               MAX_ENVS=20
@@ -310,7 +290,8 @@ jobs:
 
           # Create PR namespace and PR hostname env var
           - name: Create namespace and env vars
-            if: ${{ env.SKIP_TESTS != 'true' && env.GEN3_INSTANCE_TYPE == 'HELM_LOCAL' }}
+            if: ${{ env.SKIP_TESTS != 'true' }}
+            id: create_ns
             # Change the HOSTNAME with full domain name
             run: |
               if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
@@ -322,31 +303,7 @@ jobs:
               fi
               echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV
               echo "HOSTNAME=$HOSTNAME" >> $GITHUB_ENV
-              namespace_exists=$(kubectl get namespace "$NAMESPACE" --no-headers --ignore-not-found)
-              if [ -n "$namespace_exists" ]; then
-                echo "Namespace $NAMESPACE exists, performing teardown..."
-                helm delete $NAMESPACE -n $NAMESPACE || true
-                kubectl delete ns $NAMESPACE
-              fi
-              kubectl create namespace $NAMESPACE
-
-          # Select an unlocked environment
-          # If an env is specified in a PR label use it, else pick one from the pool
-          - name: Select CI environment
-            if: ${{ env.SKIP_TESTS != 'true' && env.GEN3_INSTANCE_TYPE == 'ADMINVM_REMOTE' }}
-            id: select_ci_env
-            run: |
-              env_label=$(gh api repos/$REPO_FN/pulls/$PR_NUM --jq '.labels | map(select(.name | startswith("jenkins-"))) | .[0].name')
-              echo "$env_label"
-              if [[ $env_label != "" && $env_label != null ]]; then
-                echo "Found PR label $env_label"
-                poetry run python -m gen3_ci.scripts.select_ci_environment $env_label
-              else
-                poetry run python -m gen3_ci.scripts.select_ci_environment
-              fi
-              if [ $? -ne 0 ]; then
-                echo "PR_ERROR_MSG=Failed to select CI environment" >> $GITHUB_ENV
-              fi
+              kubectl create namespace $NAMESPACE || true
 
           - name: Get modified folders
             # This is applicable for Manifest PRs only
@@ -355,31 +312,23 @@ jobs:
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: |
               PR_FILES=$(gh api repos/$REPO_FN/pulls/$PR_NUM/files --jq '.[].filename')
-              if [ "$GEN3_INSTANCE_TYPE" == "HELM_LOCAL" ]; then
-                UPDATED_FOLDERS=$(echo "$PR_FILES" | grep -v "^.github/" | awk -F'/' '{if ($1 != ".github" && NF > 1) print $1"/"$2}' | sort -u | tr '\n' ',' | sed 's/,$//')
-              else
-                UPDATED_FOLDERS=$(echo "$PR_FILES" | grep '/.*' | sed 's|/.*||' | grep -v "^.github$" | uniq | sort -u | tr '\n' ',' | sed 's/,$//')
-              fi
+              UPDATED_FOLDERS=$(echo "$PR_FILES" | grep -v "^.github/" | awk -F'/' '{if ($1 != ".github" && NF > 1) print $1"/"$2}' | sort -u | tr '\n' ',' | sed 's/,$//')
               echo "UPDATED_FOLDERS=$UPDATED_FOLDERS" >> $GITHUB_ENV
 
           # Apply the changes to the manifest of the selected CI environment, roll the pods and run usersync
           # Generate API keys for test users for the environment
           - name: Prepare CI environment
             id: prep_ci_env
-            if: ${{ env.SKIP_TESTS != 'true' && steps.select_ci_env.outcome == 'success' || env.GEN3_INSTANCE_TYPE == 'HELM_LOCAL' }}
+            if: ${{ env.SKIP_TESTS != 'true' && (steps.create_ns.outcome == 'success' || steps.select_ci_env.outcome == 'success') }}
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: |
               echo $UPDATED_FOLDERS
-              echo "Instance Type"
-              echo $GEN3_INSTANCE_TYPE
               mkdir $HOME/.gen3
-              if [[ "$GEN3_INSTANCE_TYPE" == "ADMINVM_REMOTE" ]]; then
-                HOSTNAME=${NAMESPACE}.planx-pla.net
-                echo "HOSTNAME=$HOSTNAME" >> $GITHUB_ENV
-              fi
-              poetry run python -m gen3_ci.scripts.prepare_ci_environment
-              if [ $? -ne 0 ]; then
+              mkdir logs
+              echo "****** Prepare CI Environment ******" > logs/gh_action_logs.txt
+              if ! poetry run python -m gen3_ci.scripts.prepare_ci_environment >> logs/gh_action_logs.txt 2>&1; then
                 echo "PR_ERROR_MSG=Failed to Prepare CI environment" >> $GITHUB_ENV
+                exit 1
               fi
 
           # This is used for running specific test suites by labeling the PR with the test class
@@ -405,8 +354,9 @@ jobs:
             if: ${{ env.SKIP_TESTS != 'true' && inputs.SERVICE_TO_TEST && steps.prep_ci_env.outcome == 'success' }}
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: |
+              echo -e "\n\n************ Run tests ************" >> logs/gh_action_logs.txt
               mkdir output
-              GEN3_INSTANCE_TYPE="$GEN3_INSTANCE_TYPE" poetry run pytest -n logical -m "${{ inputs.SERVICE_TO_TEST }} and not wip" --alluredir allure-results --no-header --dist loadscope ${{ env.TEST_LABEL }}
+              poetry run pytest -n logical -m "${{ inputs.SERVICE_TO_TEST }} and not wip" --alluredir allure-results --no-header --dist loadscope ${{ env.TEST_LABEL }} >> logs/gh_action_logs.txt 2>&1
               if [ $? -ne 0 ]; then
                 echo "PR_ERROR_MSG=Test(s) failures encountered in PR" >> $GITHUB_ENV
               fi
@@ -416,18 +366,12 @@ jobs:
             if: ${{ env.SKIP_TESTS != 'true' && !inputs.SERVICE_TO_TEST && steps.prep_ci_env.outcome == 'success' }}
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: |
+              echo -e "\n\n************ Run tests ************" >> logs/gh_action_logs.txt
               mkdir output
-              GEN3_INSTANCE_TYPE="$GEN3_INSTANCE_TYPE" poetry run pytest -n logical -m "not wip" --alluredir allure-results --no-header --dist loadscope ${{ env.TEST_LABEL }}
+              poetry run pytest -n logical -m "not wip" --alluredir allure-results --no-header --dist loadscope ${{ env.TEST_LABEL }} >> logs/gh_action_logs.txt 2>&1
               if [ $? -ne 0 ]; then
                 echo "PR_ERROR_MSG=Test(s) failures encountered in PR" >> $GITHUB_ENV
               fi
-
-          - name: Debug logging
-            if: ${{ env.SKIP_TESTS != 'true' }}
-            continue-on-error: true  # if this fails, we still need to run clean-up steps
-            run: |
-              echo steps.run_service_tests.outcome = ${{ steps.run_service_tests.outcome }}
-              echo steps.run_tests.outcome = ${{ steps.run_tests.outcome }}
 
           - name: Generate allure report
             id: generate_allure_report
@@ -445,29 +389,36 @@ jobs:
             if: ${{ env.SKIP_TESTS != 'true' && steps.generate_allure_report.outcome == 'success' }}
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: |
-              if [[ "$GEN3_INSTANCE_TYPE" == "ADMINVM_REMOTE" ]]; then
-                AWS_ACCESS_KEY_ID="${{ secrets.CI_AWS_ACCESS_KEY_ID }}" AWS_SECRET_ACCESS_KEY="${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}" aws s3 sync ./allure-report ${{ secrets.QA_DASHBOARD_S3_PATH }}/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM
+              echo -e "\n\n******* Upload reports to S3 *******" >> logs/gh_action_logs.txt
+              if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
+                DATE=$(date +%Y%m%d)
+                aws s3 sync ./allure-report s3://ci-allure-reports/nightly-run/$DATE >> logs/gh_action_logs.txt 2>&1
               else
-                if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
-                  DATE=$(date +%Y%m%d)
-                  aws s3 sync ./allure-report s3://ci-allure-reports/nightly-run/$DATE
-                else
-                  aws s3 sync ./allure-report s3://ci-allure-reports/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM
-                fi
+                aws s3 sync ./allure-report s3://ci-allure-reports/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM >> logs/gh_action_logs.txt 2>&1
               fi
               if [ $? -ne 0 ]; then
                 echo "PR_ERROR_MSG=Failed to upload allure report to s3 bucket" >> $GITHUB_ENV
               fi
 
-          - name: Archive pod logs from CI environment
-            id: archive_pod_logs
-            if: ${{ env.SKIP_TESTS != 'true' && env.GEN3_INSTANCE_TYPE == 'ADMINVM_REMOTE' && steps.prep_ci_env.outcome == 'success' || env.GEN3_INSTANCE_TYPE == 'ADMINVM_REMOTE' && steps.prep_ci_env.outcome == 'failure' }}
+          - name: Upload logs to S3
+            id: upload_gh_action_logs
+            if: ${{ env.SKIP_TESTS != 'true' && (steps.prep_ci_env.outcome == 'success' || steps.prep_ci_env.outcome == 'failure') }}
             continue-on-error: true  # if this fails, we still need to run clean-up steps
-            run: poetry run python -m gen3_ci.scripts.save_ci_env_pod_logs
+            run: |
+              echo -e "\n\n******** Upload logs to S3 ********" >> logs/gh_action_logs.txt
+              if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
+                DATE=$(date +%Y%m%d)
+                aws s3 sync ./logs s3://ci-allure-reports/nightly-run/$DATE >> logs/gh_action_logs.txt 2>&1
+              else
+                aws s3 sync ./logs s3://ci-allure-reports/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM >> logs/gh_action_logs.txt 2>&1
+              fi
+              if [ $? -ne 0 ]; then
+                echo "PR_ERROR_MSG=Failed to upload allure report to s3 bucket" >> $GITHUB_ENV
+              fi
 
           - name: Generate markdown report
             id: generate_md_report
-            if: ${{ env.SKIP_TESTS != 'true' && steps.generate_allure_report.outcome == 'success' || steps.archive_pod_logs.outcome == 'success' }}
+            if: ${{ env.SKIP_TESTS != 'true' && steps.generate_allure_report.outcome == 'success' }}
             continue-on-error: true
             # It is possible for env is prepped but tests error out, the pod logs will help in debugging env issues
             run: |
@@ -482,19 +433,18 @@ jobs:
                   echo -e "\nPlease find the detailed integration test report [here](https://allure.ci.planx-pla.net/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM/index.html)" >> output/report.md
                 fi
               fi
-              if [ "${{steps.archive_pod_logs.outcome}}" == "success" && $GEN3_INSTANCE_TYPE == "ADMINVM_REMOTE" ]; then
-                if [ ! -d output ]; then
-                  mkdir output
+              if [ "${{ steps.upload_gh_action_logs.outcome }}" == "success" ]; then
+                if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
+                  DATE=$(date +%Y%m%d)
+                  echo -e "\nPlease find the Github Action logs [here](https://allure.ci.planx-pla.net/nightly-run/$DATE/gh_action_logs.txt)" >> output/report.md
+                else
+                  echo -e "\nPlease find the Github Action logs [here](https://allure.ci.planx-pla.net/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM/gh_action_logs.txt)" >> output/report.md
                 fi
-                if [ ! -f "output/report.md" ]; then
-                  touch "output/report.md"
-                fi
-                echo -e "\nPlease find the ci env pod logs [here]($POD_LOGS_URL)" >> output/report.md
               fi
 
           - name: Render report to the PR
             id: publish_md_report
-            if: ${{ env.SKIP_TESTS != 'true' && github.event_name == 'pull_request' && steps.generate_allure_report.outcome == 'success' || steps.archive_pod_logs.outcome == 'success' }}
+            if: ${{ env.SKIP_TESTS != 'true' && github.event_name == 'pull_request' && steps.generate_allure_report.outcome == 'success' }}
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: gh pr comment $PR_NUM --body-file output/report.md -R $REPO_FN
             env:
@@ -502,7 +452,7 @@ jobs:
 
           - name: Generate Slack report
             id: generate_slack_report
-            if: ${{ env.SKIP_TESTS != 'true' && steps.generate_allure_report.outcome == 'success' || steps.archive_pod_logs.outcome == 'success' }}
+            if: ${{ env.SKIP_TESTS != 'true' && (steps.upload_allure_report.outcome == 'success' || steps.upload_gh_logs.outcome == 'success') }}
             continue-on-error: true # if this fails, we still need to run clean-up steps
             run: poetry run python -m gen3_ci.scripts.generate_slack_report
 
@@ -517,12 +467,6 @@ jobs:
               payload-file-path: "./${{ inputs.WORKING_DIR }}/slack_report.json"
               payload-templated: true
 
-          - name: Release CI environment
-            id: release_ci_env
-            if: ${{ (env.SKIP_TESTS != 'true' && env.GEN3_INSTANCE_TYPE == 'ADMINVM_REMOTE' && steps.select_ci_env.outcome == 'success') || (cancelled() && env.GEN3_INSTANCE_TYPE == 'ADMINVM_REMOTE') }}
-            continue-on-error: true  # if this fails, we still need to run clean-up steps
-            run: poetry run python -m gen3_ci.scripts.release_ci_environment
-
           - name: Mark workflow as failed for unsuccessful test runs
             if: ${{ env.SKIP_TESTS != 'true' && steps.run_service_tests.outcome != 'success' && steps.run_tests.outcome != 'success' }}
             run: echo "Test run was unsuccessful, marking workflow as failed" && exit 1
@@ -530,8 +474,4 @@ jobs:
           - name: Cleanup
             if: ${{ env.SKIP_TESTS != 'true' }}
             run: |
-              if [[ "$GEN3_INSTANCE_TYPE" == "ADMINVM_REMOTE" ]]; then
-                poetry run python -m gen3_ci.scripts.clean_up_jenkins
-              elif [[ "$GEN3_INSTANCE_TYPE" == "HELM_LOCAL" ]]; then
-                poetry run python -m gen3_ci.scripts.teardown_ci_env
-              fi
+              poetry run python -m gen3_ci.scripts.teardown_ci_env
