uncomment

diff --git a/.github/workflows/python_package_index_publish.yaml b/.github/workflows/python_package_index_publish.yaml
--- a/.github/workflows/python_package_index_publish.yaml
+++ b/.github/workflows/python_package_index_publish.yaml
@@ -84,22 +84,22 @@ jobs:
           echo github.ref=${{ github.ref }}
         shell: bash
 
-      # - name: Publish to Test PyPI
-      #   id: test-pypi
-      #   if: ${{ inputs.DO_TEST_PUBLISH_FIRST && startsWith(github.ref, 'refs/tags/') }}
-      #   run: |
-      #     echo "Attempting a test publish before a real one. Note that a real one will only trigger on tags"
-      #     poetry publish -n -vv -r testpypi
+      - name: Publish to Test PyPI
+        id: test-pypi
+        if: ${{ inputs.DO_TEST_PUBLISH_FIRST && startsWith(github.ref, 'refs/tags/') }}
+        run: |
+          echo "Attempting a test publish before a real one. Note that a real one will only trigger on tags"
+          poetry publish -n -vv -r testpypi
 
-      # - name: Publish to PyPI
-      #   id: prod-pypi
-      #   if: ${{ (!inputs.DO_TEST_PUBLISH_FIRST || (inputs.DO_TEST_PUBLISH_FIRST && steps.test-pypi.outcome == 'success')) && startsWith(github.ref, 'refs/tags/') }}
-      #   run: |
-      #     echo "Since this is a tagged release, do a real publish"
-      #     poetry publish -n -vv
+      - name: Publish to PyPI
+        id: prod-pypi
+        if: ${{ (!inputs.DO_TEST_PUBLISH_FIRST || (inputs.DO_TEST_PUBLISH_FIRST && steps.test-pypi.outcome == 'success')) && startsWith(github.ref, 'refs/tags/') }}
+        run: |
+          echo "Since this is a tagged release, do a real publish"
+          poetry publish -n -vv
 
-      # - name: If Publish to PyPI Did Not Succeed, Fail Job
-      #   if: ${{ steps.prod-pypi.outcome != 'success' }}
-      #   run: |
-      #     echo "Since this is a tagged release, and the real publish failed or didn't run, fail the job"
-      #     exit 1
+      - name: If Publish to PyPI Did Not Succeed, Fail Job
+        if: ${{ steps.prod-pypi.outcome != 'success' }}
+        run: |
+          echo "Since this is a tagged release, and the real publish failed or didn't run, fail the job"
+          exit 1
